### ISSUE TITLE
Course Setup: when deleting a course, warn the user if the course has other assignments

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#375]
The course setup page allows instructors to delete courses. When a course is deleted, the user should get a warning about what will happen to other assignments in the course.

**Comment by ald32** [comment]
Just discussed this with Anna, and we decided that an instructor should not be able to delete a course if there are other assignments in it. They will have to delete the assignments individually instead of deleting them all together. The instructor should encounter an error message that says:

This course cannot be deleted as there are other assignments within this course. If you would like to delete all of the assignments within the course, please delete the assignments individually using the trash can icon on the dashboard.

'OK'

**Comment by annagav** [comment]
Fixed by #514

**Comment by ald32** [comment]
The strategy of adding a message in red in the window is good, but I do feel like instructors may need guidance on what they should do if they would like to delete a course and hte message that I wrote above seems to address that.
