### ISSUE TITLE
Preview indicator

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#483]
As an instructor, I need a banner or similar to remind me when I'm previewing my assignment. 

Suggestion for now is to use the space currently used for Sign In and Sign Out, since Preview isn't really in either of those states (although the instructor must be logged in to preview).

**Comment by ald32** [comment]
The other option is to put a 'Preview Mode' message on the very right side of the Assignments/Experiments bar at the top of each page.

**Comment by ald32** [comment]
I'm testing out Canvas right now and they have a nice feature for instructors to see what the course page will look like for students. In the 'student view', the whole page is outlined, in this case with a hot pink line, and there is a bar at the bottom that lets the instructor know that they are in student view. The bar also provides two buttons to allow instructors to reset the student view or leave the student view. I think that something like this could be really good for the 'preview' mode in the assignment builder. It's very noticeable and lets the instructor know that they are in this other mode - and it also lets them return to the instructor view very easily. What do you think?

![screen shot 2016-03-08 at 10 03 41 am](https://cloud.githubusercontent.com/assets/1855065/13611046/607a2f64-e515-11e5-8d51-67eb6f7eea32.png)

**Comment by annagav** [comment]
The assignment builder looks significantly different from the student view. It is a completely separate app. They never exist within the same tab and you cannot go back and forth by a button click. It opens in a different tab, so the two apps never really intersect.

I think it is redundant to outline it, because when you preview an assignment you are actually doing the assignment as a guest (just like when you do `try an experiment`).

**Comment by annagav** [comment]
@laleman decided to close this.
