### ISSUE TITLE
AB: FACS only one button that changes state

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#590]
Instead of having 3 buttons for each sample (select, add, edit), use one button that changes state. Before a histogram exists, the button is "Add Histogram" which opens to the drawing tool (with an option to select a pre-existing histogram). After a histogram exists (whether drawn or pre-existing) the button label changes to "Edit Histogram"

**Comment by annagav** [comment]
@ald32, In the design documents it looks like the buttons disappear when graph is chosen, and the edit 'pencil' icon enables and becomes green. I think I like this flow better.

**Comment by ald32** [comment]
@annagav, so let's go through what happens. Do you mean that an instructor will first see the 'Add Histogram' button on the screen when they first navigate to the screen? Then once a histogram is added, then the edit icon will appear and work? I do like how we discussed simplifying the interface so that there isn't a button and an icon, which may be unclear to the instructor in terms of what they are supposed to do. Let me know if should do a quick google chat or something.

**Comment by annagav** [comment]
I think it won't be confusing if the edit icon is there disabled and grey colored, because the only thing you can click is the 'add histogram' button. Then, when the histogram is selected the button disappears and edit icon becomes green.

**Comment by ald32** [comment]
Ok let's give it a try! We can then see what it's like when we can interact with it.

**Comment by pdpinch** [comment]
This should be done already. Closing.
