### ISSUE TITLE
FACS: change "canvas" step to "Histogram"

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#623]
This is the form where users configure their axes, i.e. whether they are linear or logarithmic, the maximum value and the tick values. 

Also, the blue text at the top of the form should be updated to use the same name.

<img width="766" alt="screen shot 2016-03-31 at 12 12 00 pm" src="https://cloud.githubusercontent.com/assets/430126/14182587/e0a072f8-f739-11e5-9de4-951f4b89d57e.png">

**Comment by pdpinch** [comment]
@ald32 @laleman please advise

**Comment by ald32** [comment]
The blue heading at the top should be: Histogram

I looked at Prism which is a great graphing program and took a snapshot of what the options look like in the program. There are more options than we need (see the image), but see what you think of the pared down suggestions below. 
<img width="823" alt="screen shot 2016-03-31 at 10 40 38 am" src="https://cloud.githubusercontent.com/assets/1855065/14185113/41927e60-f72d-11e5-9448-809fce3b0967.png">

X-axis 
Please select the scale, range, and ticks for the x-axis.
Scale 
[dropdown menu: linear, logarithmic]
Range 
Minimum [text box, 0 as the default]               Maximum [text box, 200 as the default]
Additional Ticks
[text box, with 50, 100, 150 as the defaults]

The other option instead of having the 'additional ticks' text box is to use the following instead:
Regularly spaced ticks
Tick interval [text box with 50 as the default]

@pdpinch @annagav @laleman - let me know what you think.
