### ISSUE TITLE
Microscopy: provide example values for conditions

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#650]

**Comment by ald32** [comment]
Antibody-labeling IF: EGFR A488
Dye/Stain: H&E
Fluorescence: GFP
Immunohistochemistry (not sure if we have this right now? Do we have an example of this from another exercise that we can pull from? maybe the old microscopy usability exercise?): EGFR

are there any other categories @annagav ?

**Comment by annagav** [comment]
Here is the list we talked about before:

dye/stain - bright field
dye/stain - fluorescence
antibody labeling - IF
antibody labeling - IHC
fluorescence
brightfield

We should probably add all of them, since we don't let the instructor define his own. Would you have a default condition for each one of these?

**Comment by annagav** [comment]
@ald32 and @laleman, Could you please take a look at my comment above?

**Comment by ald32** [comment]
Sorry for the delay @annagav. Yes we should include all of them since instructors can't modify the list on their own. 

The list of analyses should be:
dye/stain (brightfield) - H&E (or Hematoxylin & Eosin if you have enough room)
dye/stain (fluorescence) - DAPI
antibody labeling IF - histone H3 antibody
antibody labeling IHC - histone H3 antibody
fluorescence -> GFP-tagged protein
brightfield -> (N/A)

Brightfield on its own won't have a condition. I wrote in N/A because I think that the best thing to use in place of a real condition.

**Comment by annagav** [comment]
@laleman, @ald32 I think we need to add another input field for short name for each condition, that is used in small tabs in microscopy analysis step in StarCellBio.

**Comment by ald32** [comment]
@annagav - i think that's a good idea. Can you implement this? Do you need anything from us?

**Comment by annagav** [comment]
I would need short names for ' histone H3 antibody' and 'GFP-tagged protein'.

**Comment by ald32** [comment]
How many characters fit in the tab?
'His H3 antibody' OR 'His H3'
'GFP-tagged prot' OR 'GFP protein'

**Comment by annagav** [comment]
With filters:
dye/stain (brightfield) - H&E (or Hematoxylin & Eosin if you have enough room)
dye/stain (fluorescence) - DAPI (filters)
antibody labeling IF - histone H3 antibody (filters)
antibody labeling IHC - histone H3 antibody
fluorescence -> GFP-tagged protein ( filters)
brightfield -> (N/A)
