### ISSUE TITLE
AB: Dropdown styling

### ISSUE THREAD

**Issue by pdpinch** [starteam/starcellbio_html#665]
In choosing analysis in each experiment's sample prep, the drop-down arrow isn't displaying.

**Comment by annagav** [comment]
In order to get the select dropdown arrows, we have to compromise the border radius of the select field, since many native select menus have rounded corners that cannot be modified via `border-radius` properties. 
![screen shot 2016-07-28 at 9 07 12 am](https://cloud.githubusercontent.com/assets/7574259/17213639/29aa0ce0-54a3-11e6-8cde-15db0032a792.png)

**Comment by pdpinch** [comment]
This seems OK to me.
